### ISSUE TITLE
Warn of upcoming orders when setting a client status

### ISSUE THREAD

**Issue by guillaumep** [santropolroulant/sous-chef#64]
As a client program manager, when I change a client status, I want to be informed of upcoming orders for that client so that I can go and cancel these orders if needed.

**Comment by guillaumep** [comment]
@brookesantropol Code done, will install in staging at the end of the day so you can test.

Here's a screenshot of the changes:

<img width="921" alt="Capture d’écran, le 2021-03-05 à 16 47 36" src="https://user-images.githubusercontent.com/1195230/110177200-961cb500-7dd2-11eb-8912-814f701e9c10.png">

**Comment by brookesantropol** [comment]
Need to be able to approve the change in status AND THEN modify the upcoming order. Otherwise, clicking on view order does not complete the status modification, and the user may forget to go back and complete the process.

Need to be able to Cancel order, rather than delete order, when viewing the order.

**Comment by brookesantropol** [comment]
Could also add Cancel order button the alert that pops up, next to the view order button.

**Comment by guillaumep** [comment]
As a short term solution, I will hide the "Actions" column from the dialog, so the user don't have a link to get out of the dialog (as the user can completely forget to confirm the status change).
